spatie/laravel-event-sourcing

- docs/advanced-usage/replaying-events.md
The correct method name for detecting replay should be `Spatie\EventProjector\Facades\Projectionist::isReplaying();`.
> Fixed method name for replay detection

- stubs/create_stored_events_table.php.stub
- tests/TestClasses/FakeUuid.php
Using a UUID field, rather than a varchar, to store the UUIDs in Postgres has a storage and performance benefit (the UUID field only occupies [16 bytes](https://github.com/postgres/postgres/blob/master/src/include/utils/uuid.h#L18) as opposed to the 37 bytes the varchar is currently occupying).
Since the [MySQL grammar](https://github.com/illuminate/database/blob/master/Schema/Grammars/MySqlGrammar.php#L735) handles the lack of a native UUID type there is no negative impact on MySQL for this change.
This simply changes the stub and has no impact on existing codebases. I additionally updated the FakeUUID class to generate a valid V4 UUID so all the tests still pass on both MySQL and Postgres.
> Use a UUID field when possible for storing UUIDs

- config/event-sourcing.php
- docs/installation-setup.md
- src/HandleDomainEventJob.php
- src/HandleStoredEventJob.php
Both the config and documentation reference a missing Spatie\EventSourcing\HandleDomainEventJob class. At first I assumed this was a typo for the HandleStoredEventJob class, however, the class is final and can't be extended.
Instead, as hopefully makes more sense, I implement a HandleDomainEventJob interface in a non-breaking way that follows the rest of the codebase. I additionally updated the documentation to reference implementing rather than extending the new HandleDomainEventJob interface.
> Implemented missing HandleDomainEventJob interface

- src/AggregateRoot.php
This fixes the "method not found" errors in IDEs and static analysis tools like phpstan.
---
Followup for #28
> Provide docblocks to AggregateRoot class

- docs/using-aggregates/testing-aggregates.md
Fixes a couple of typos and adds explanation of using the `Projectionist::withoutEventHandlers()` method.
In reference to documentation suggestion made in #30.
> Documentation addition for using `Projectionist::withoutEventHandlers()` 

- src/Projectionist.php
Today I tried to replay a projection not from beginning of the event stream, but from a certain event id. This worked in the "old" event projector packages, but to my surprise it showed the following:
A quick look in the code revealed, that the wrong method was called... Here's the fix.
* Call correct method
* Organize params, as the first one now should be the starting id
* Remove coalesce operator (param has to be int and never is null)
> Fix replay from specified event id

- config/event-sourcing.php
- src/AggregateRoot.php
- src/EloquentSnapshotRepository.php
- src/EloquentStoredEventRepository.php
- src/Exceptions/InvalidEloquentSnapshotModel.php
- src/Models/EloquentSnapshot.php
- src/Models/EloquentStoredEvent.php
- src/Snapshot.php
- src/SnapshotRepository.php
- src/StoredEvent.php
- src/StoredEventRepository.php
- stubs/create_snapshots_table.php.stub
- stubs/create_stored_events_table.php.stub
- tests/AggregateRootTest.php
- tests/TestCase.php
- tests/TestClasses/AggregateRoots/AccountAggregateRoot.php
This implements snapshotting of AggregateRoots
- Adds a `snapshot()` method to the AggregateRoot which creates a new Snapshot
- AggregateRoots track a `version` number, which increments each time an event is applied
- Persisting the events persists them with the version number
- The AggregateRoot has a `getState` and `useState` function to determine the state that is saved and retrieved from the snapshot, by default all properties on the class are stored in the snapshot
- When initializing an AggregateRoot, we check if there is a snapshot, if there is we load the state first, then retrieve and reconstitute from all events that happened after the snapshot.
- All public properties on an aggregate are stored as the state of the snapshot, in the tests this is the `$balance` property of the …
> Snapshotting AggregateRoot

- src/Console/ReplayCommand.php
- src/EloquentStoredEventRepository.php
- src/StoredEventRepository.php
LazyCollections count implementation iterates over all results. The replay command counts twice, so we end up iterating three times. By moving the count operation to the database and using the result in a variable we are able to get down to a single iteration.
Our system currently has around 300'000 stored events. To replay a projection, the command looped 600'000 times only to check if there are events and to display the progress bar, delaying the actual replay by several minutes.
This PR is aiming at version 1, because the upgrade to PHP 7.4 is planned later this year.
> fix slow replay

- src/DiscoverEventHandlers.php
We use docker containers,
Our project sits at `/app` in the filesystem, meaning we have paths like `/app/app/Http/Controller.php`
With the current setup it was meaning the namespace of `\App\Http\Controllers\Controller` was becoming `\Http\Controllers\Controller`
> Only replace the first instance of the basePath

- src/EventSerializers/JsonEventSerializer.php
- tests/EventSerializers/EventSerializerTest.php
- tests/TestClasses/Events/EventWithDatetime.php
Run test as:
`vendor/bin/phpunit --filter EventSerializerTest`
You will notice the bug:
```
1) Spatie\EventSourcing\Tests\EventSerializers\EventSerializerTest::it_can_deserialize_an_event_with_datetime
Symfony\Component\Serializer\Exception\MissingConstructorArgumentsException: Cannot create an instance of DateTimeImmutable from serialized data because its constructor requires parameter "time" to be present.
```
> add tests for datetime deserialization

- docs/advanced-usage/replaying-events.md
The docs currently reference that the `--projector` option is available when replaying events. This has actually been changed to an option, therefore no `--projector` prefix required.
Looks like this change was introduced [here](https://github.com/spatie/laravel-event-sourcing/commit/fbb439093285522145ec4c9a8e5e70c268b4a0c7#diff-219d2a262b5ca12ebf45af61b8915600)
> Fixed event replay command docs

- docs/using-aggregates/creating-and-configuring-aggregates.md
- docs/using-aggregates/writing-your-first-aggregate.md
I removed the Final keyword from the examples in the docs for using the CLI to generate aggregates as the stubs no longer uses Final.
> Remove the Final keyword from code generation examples

- src/AggregateRoot.php
- src/FakeAggregateRoot.php
- tests/FakeAggregateRootTest.php
Calling `persist` on an aggregate root will clear the `recordedEvents` array. This means that if you're calling persists within a faked aggregate root, assertions will fail because the recorded events array is empty. 
I'd suggest to keep track of all applied events as well, which will never get cleared.
> Add applied events support

- docs/using-aggregates/snapshots.md
- src/AggregateRoot.php
Otherwise properties like `aggregateVersion` and `aggregateVersionAfterReconstitution` are getting into the event properties.
> Only include public properties of the aggregate when snapshotting

- docs/advanced-usage/using-your-own-event-serializer.md
- src/EventSerializers/EventSerializer.php
- src/StoredEvent.php
- tests/EventSerializers/EventSerializerTest.php
- tests/TestClasses/EventSerializer/UpgradeSerializer.php
This is a first pass suggestion on how to implement an upgrade backwards compatible event versions. 
For example if we had an event like `AccountCreated` and stored the open date as `2019-03-43 12:30:00`. This event payload is v1. 
In later versions of the app, we're going international and so the open date now needs a timezone attached to it like `2019-03-43 12:30:00 +00:00`.
We change the code to include the timezone and it's now v2 of the event payload. 
When we replay events we expect the latest version of the event payload in order to function correctly. This PR allows the event serializer to upgrade the event live so it can be transformed to the latest version.
> Pass metadata to serializer to allow events to be upgraded

- docs/advanced-usage/adding-and-removing-projectors-and-reactors.md
The singular method name was used, while this should be the plural method name.
> Fixed the docs for addReactors and addProjectors

- config/event-sourcing.php
1. Correct EloquentStoredEventRepository name in comment
2. Correct EloquentSnapshotRepository name in comment
3. Correct EventSerializer name in comment
4. Correct grammar of "class names"
> config file comment corrections 

- src/EloquentStoredEventRepository.php
Make EloquentStoredEventRepository consistently use the uuid model scope for queries.
This allows for overriding the scope for use cases such as using the efficientUuid package
> Replace model where clause with uuid model scope

- stubs/create_snapshots_table.php.stub
- stubs/create_stored_events_table.php.stub
Ensures many more events and snapshots can be recorded before an int overflow error occurs.
Also bring it inline with the default int type for Laravel 7 id column types.
Regular unsigned int is not large enough for event heavy Event Sourced systems.
> Default to BigIncrements on package table stubs

- docs/using-projectors/making-sure-events-get-handled-in-the-right-order.md
Whilst pulling down v4 and having a play around I realised at the queuing section of the documentation was still at v2. If I find anything else I'll drop it in this morning. I won't be offended if you want to reword it 👍
> Updates implementation of how to queue a projector

- docs/using-aggregates/snapshots.md
This was changed in the code in https://github.com/spatie/laravel-event-sourcing/commit/2e927470914a65c19a33037d1f3e38508c78fff3 but the change was not reflected in this line in the docs.
> Update snapshots.md to reflect current code

- README.md
A simple suggestion: the link to the documentation may benefit from the introduction part of the document Because navigating to https://docs.spatie.be/laravel-event-sourcing/v4 simply opens the document's blank section but, https://docs.spatie.be/laravel-event-sourcing/v4/introduction opens the introduction directly.
This PR makes the little change to the link in the Readme.md file.
> PS: I am not sure what branch is appropriate to make the Pull Request to, this is why I chose master.
> Update Readme with Link to open the doc's introduction directly

- docs/using-aggregates/testing-aggregates.md
- src/AggregateRoots/FakeAggregateRoot.php
- tests/FakeAggregateRootTest.php
Sometimes you'd like to test if a specific event is fired from the method of an aggregate, without caring about other events that the method might fire. For this, I've added a `assertEventRecorded` to the fake aggregate root. 
So we could use: 
`->assertEventRecorded(new DummyEvent(3));`
While `DummyEvent(4)` is also fired from the same method.
> Add assertion that specific event is recorded

- config/event-sourcing.php
- docs/using-aggregates/creating-and-configuring-aggregates.md
- src/AggregateRoots/AggregateRoot.php
- src/StoredEvents/EventSubscriber.php
- src/StoredEvents/StoredEvent.php
- tests/AggregateRootTest.php
- tests/EventSubscriberTest.php
Currently when an event is recorded from within an aggregate root, it is not dispatched on Laravel's event bus. 
This non breaking, configurable change would allow for aggregate roots to dispatch the events when the events are persisted.
> Allow events to be dispatched from an aggregate root

- composer.json
- src/EventSerializers/JsonEventSerializer.php
- src/Support/CarbonNormalizer.php
- tests/EventSerializers/EventSerializerTest.php
- tests/TestClasses/Events/EventWithCarbon.php
Using `Carbon` dates in events doesn't currently work out of the box. The current implementation of the DateTimeNormalizer only allows you to use PHP's `DateTime` which misses out on some useful Carbon functionalities. To use Carbon dates, you need to implement your own [`EventSerializer`](https://github.com/spatie/laravel-event-sourcing/blob/master/src/EventSerializers/EventSerializer.php) and add a `Normalizer` that supports the (de)normalization of Carbon instances.
As the standard date implementation is Carbon and this package is built for Laravel, I would like to suggest to include a `CarbonNormalizer` to improve the developer experience for those who use Carbon datetimes in their events.
> Support Carbon dates in events

- README.md
I keep using this link instead of the one at the top of the README for some reason and figured I may as well fix it!
> Fix link to v1 docs in README

- docs/using-projectors/creating-and-configuring-projectors.md
- docs/using-projectors/writing-your-first-projector.md
Updates a presumably outdated reference to an empty interface that doesn't exist, so that it now matches the code samples immediately below :smiley:
> Update documentation to match the code

- config/event-sourcing.php
- docs/advanced-usage/preparing-events.md
- src/EventSerializers/JsonEventSerializer.php
- src/Support/ModelIdentifierNormalizer.php
- tests/TestClasses/Events/MoneyAddedEvent.php
- tests/TestClasses/Events/MoneyAddedEventWithQueueOverride.php
- tests/TestClasses/Events/MoneySubtractedEvent.php
The current implementation that uses `SerializesModels` does not work with collections of models, and also fails if you type hint your StoredEvent's properties with the model class or `Collection`. This solves that by introducing a new `ModelIdentifierNormalizer` instead.
Under the hood, it defers to the same logic that `SerializesModels` uses, but it does it as part of the serialization/normalization chain.
I've also made the normalization chain configurable, so that it's not necessary to re-implement the serializer just to add custom normalizers. I'm happy to remove that customization if you feel it's too much, but I do think it's worthwhile.
This could be considered a breaking change, but I don't think it is—if `SerializesModels` exists on the event, it will still work correctly.
> Model and Collection normalization

- docs/using-aggregates/creating-and-configuring-aggregates.md
- src/AggregateRoots/AggregateRoot.php
- tests/AggregateRootTest.php
This non-breaking PR will add a non-static method to load in the UUID so that the AggregateRoot can be injected.
> Added loadUuid function to avoid static retrieve function

- config/event-sourcing.php
fix 'should implement' paths/namespaces for current version
Change reference url for caching event handlers to current v4 version url in the docs
> Fix Paths and Reference URL in event-sourcing.php config file

- src/StoredEvents/Models/EloquentStoredEvent.php
- src/StoredEvents/Repositories/EloquentStoredEventRepository.php
- src/StoredEvents/StoredEvent.php
- tests/EloquentStoredEventRepositoryTest.php
- tests/Models/StoredEventTest.php
Currently, when you call `EloquentStoredEventRepository::persist()`, this persists the event to the database and then immediately returns the deserialized version of that event. When the attributes on the event are all basic data types like `string` and `int`, the performance hit associated with serializing and deserializing is negligible. When one or more attributes on the event are eloquent models, this can result in an N+1 issue.
This PR introduces the concept of the "original event" to `StoredEvent` and `EloquentStoredEvent`. If the original event is provided and/or present, these models can re-use it. If not, the models can instantiate it from the serialized data.
> Re-use existing instance of ShouldBeStored when possible

- tests/Models/StoredEventTest.php
- tests/ProjectionistTest.php
- Using the `aasertSame` to assert expected is `0` strictly.
- Using the `assertInstanceOf` to assert expected is same as result instance.
> Improve assertions

- src/EventSourcingServiceProvider.php
When applying the custom directory structure as suggested by the "Laravel Beyond Crud" book, the event discovery fails as it uses the base path to guess the class names from the file names.
https://github.com/spatie/laravel-event-sourcing/blob/05d0aa072ac6385aebda0d84519a8aa389fe2813/src/Support/DiscoverEventHandlers.php#L72-L83
So a Projector placed at `./src/App/Projectors/UsersProjector.php` is guessed as this class `Src\App\Projectors\UsersProjector`, which does not exist.
By allowing a user to specify a custom config key one could add this config key:
~~~php
'auto_discover_base_path' => base_path('src'),
~~~
And have the `src` part ignored.
As it is seems to be an edge case, I didn't add a config key on the config stub.
If you prefer me to do so, please let know and I will update the …
> Allow custom path as a base path

- CHANGELOG.md
- src/AggregateRoots/AggregateRoot.php
- src/AggregateRoots/FakeAggregateRoot.php
- src/Enums/MetaData.php
- src/StoredEvents/Repositories/EloquentStoredEventRepository.php
- src/StoredEvents/ShouldBeStored.php
- stubs/create_stored_events_table.php.stub
- tests/AggregateRootTest.php
Fix for #170 
Note that a manual migration is required for this fix to work, and that `AggregateRoot::$allowConcurrency` cannot be used anymore if you've run that migration. Details can be found in the changelog.
> Race condition fix

- config/event-sourcing.php
Follow up of PR #202 
This PR adds a config key to the config stub to make it easier to specify a base path when auto-scanning for projectors and reactors.
> Add config key to stub

- src/AggregateRoots/FakeAggregateRoot.php
I guess `$whenResult` should not be a string and it was type-hinted by mistake.
For example, my simple test case looks like:
```php
AccountAggregate::fake()
->given(new AccountCreated($account))
->when(fn(AccountAggregate $aggregate) => $aggregate->deposit($transaction))
->assertEventRecorded(new Deposited($transaction))
->assertNotRecorded(Withdrawn::class);
```
After upgrade to v5 it fails with the following error:
```php
TypeError : Cannot assign App\Aggregates\AccountAggregate to property Spatie\EventSourcing\AggregateRoots\FakeAggregateRoot::$whenResult of type ?string
/home/vagrant/code/pfm/vendor/spatie/laravel-event-sourcing/src/AggregateRoots/FakeAggregateRoot.php:40
/home/vagrant/code/pfm/tests/Unit/Aggregates/AssetAggregateTest.php:41
```
> `$whenResult` should not be a string

- database/migrations/create_snapshots_table.php.stub
- database/migrations/create_stored_events_table.php.stub
`jsonb` is generally considered [more performant](https://www.compose.com/articles/faster-operations-with-the-jsonb-data-type-in-postgresql/) than `json` 
on db's that don't support `jsonb`, Laravel will automatically fallback to `json`
> small suggestion: jsonb columns instead of json

- src/AggregateRoots/AggregateRoot.php
When using a static analysis tool such as PHPStan, a type error is returned when using the following code snippet.
```php
namespace App\Aggregates;
use Spatie\EventSourcing\AggregateRoots\AggregateRoot;
class AccountAggregate extends AggregateRoot
{
public function createAccount(string $name, string $userId): self
{
return $this->recordThat(new AccountCreated($name, $userId));
}
}
```
```
Method App\Aggregates\AccountAggregate::add() should return App\Aggregates\AccountAggregate but returns Spatie\EventSourcing\AggregateRoots\AggregateRoot.
```
The problem is with the _short_ notation directly returning the result of the `recordThat` call. The return type resolves to `Spatie\EventSourcing\AggregateRoots\AggregateRoot`, instead of the current class due to the `self` return type. However, …
> Fix AggregateRoot return types for static analysis

- config/event-sourcing.php
- docs/advanced-usage/discovering-projectors-and-reactors.md
- docs/getting-familiar-with-event-sourcing/the-traditional-application.md
- docs/getting-familiar-with-event-sourcing/using-aggregates-to-make-decisions-based-on-the-past.md
- docs/getting-familiar-with-event-sourcing/using-projectors-to-transform-events.md
Some urls still point to v4 which can cause confusion. This PR fixes that.
PS. Can the `hacktoberfest-accepted` label be added on the PR? 🥳
> Fix urls pointing to previous version

- src/StoredEvents/Repositories/EloquentStoredEventRepository.php
In one of my projects I have several millions of events and when I tried to replay them all, my process was dying because of being out of memory. I have solved this issue by changing cursor() into lazyById()
> Changed cursor() into lazyById() to preserve memory when working with large amount of events

- tests/VersionedEventTest.php
Phpunit tests failed in `a_versioned_event_can_be_restored` method of `tests/VersionedEventTest.php` due to 'uuid' property not being passed. As I have seen, event was being given `name` instead of `uuid` argument with correct value, so I have simply renamed property and test passes once again.
> Fixed tests/VersionedEventTest.php::a_versioned_event_can_be_restored 

- composer.json
This change is required because lazyById method is available from illuminate/database 8.34 version.
> Set minimum version of illuminate/database to ^8.34

- docs/advanced-usage/replaying-events.md
```
public function onAccountCreated(StoredEvent $storedEvent, AccountCreated $event) {
Account::create(array_merge($event->accountAttributes, ['created_at' => $storedEvent->created_at, 'updated_at' => $storedEvent->created_at]));
}
```
I was trying to find out how docs writer [getting](https://spatie.be/docs/laravel-event-sourcing/v5/advanced-usage/replaying-events#models-with-timestamps) `$storedEvent` instance in event arguments and found a way save code line using ShouldBeStored method. It looks cleaner.
Also if you are planning of accepting this pull-request. Perhaps we should add the functionality to return `createdAt` value using `app.timezone` config property?
> docs: update 'Models with timestamps' section

- src/AggregateRoots/AggregateRoot.php
- src/AggregateRoots/FakeAggregateRoot.php
This issue solves #276 
I assume the `persist` was used to clear the events so that we could easily see what events were recorded during the `when` stage. 
The [first POC](https://github.com/spatie/laravel-event-sourcing/commit/d6814bcd6ef63ffc573cf8350c1bbce766620dd2) of this was to simply call the `getAndClearRecordedEvents` on the AggregateRoot. 
However, we can achieve the same result by simply [remembering how many `given` events there were](https://github.com/morrislaptop/laravel-event-sourcing/blob/56fdc8f47a7ca525eafc632839db9a9c9f3f6414/src/AggregateRoots/FakeAggregateRoot.php#L34) and [removing them](https://github.com/morrislaptop/laravel-event-sourcing/blob/56fdc8f47a7ca525eafc632839db9a9c9f3f6414/src/AggregateRoots/FakeAggregateRoot.php#L174) when doing our assertions.
> Aggregate tests without db

- src/AggregateRoots/AggregateRoot.php
Follow up on #292 from https://github.com/spatie/laravel-event-sourcing/pull/292#issuecomment-979821746
If we are calling the fake method can we assume there'll be no prior events and skip the `retrieve` method.
> skip retrieve on aggregate::fake

- composer.json
https://github.com/spatie/laravel-event-sourcing/blob/eb7c3ee5ac741544c2f81083b727ff966f617e2b/composer.json#L35
5.3.8 doesn't seem to exist. All tests pass on 5.3.7. 🤷
> downgrade symfony finder

- src/AggregateRoots/FakeAggregateRoot.php
When you use something like `assertRecorded` on an aggregate root fake, it calls `getRecordedEventsWithoutUuid`:
https://github.com/spatie/laravel-event-sourcing/blob/01b17e0ba6d1795acf7b91db5475b7a0a36ea4ac/src/AggregateRoots/FakeAggregateRoot.php#L163-L175
This method removes any generated metadata from the event so that it can be safely compared, but it mutates the original event instead of cloning it or creating a new copy. This means that if you then want to use the events on the aggregate root later in your test, those metadata values are gone.
This PR just clones the event before mutating it so that if you need the generated metadata later in your test it is still available.
> Don't mutate original events in `FakeAggregateRoot::getRecordedEventsWithoutUuid`

- UPGRADING.md
We're in the process of upgrading from v4 and noticed that there's nothing in the upgrade guide. I thought I'd PR a quick overview—it's not exhaustive but it's better than nothing.
> Add v4 to v5 upgrade overview to UPGRADING.md

- src/StoredEvents/StoredEvent.php
I observed that all of the events were are sent to the queue even when projector/reactor did not extend `ShouldQueue`. While debugging found the codeblock in the StoredEvent class, where the method `shouldDispatchJob` returns a boolean if the job should be dispatched or not.
In the shouldDispatchJob method, it currently gets all allEventHandlers and checks if there is a projector or reactor which implements ShouldQueue. If the count is greater than 0, then this event handling needs to be queued.
```php
protected function shouldDispatchJob(): bool
{
/** @var \Spatie\EventSourcing\EventHandlers\EventHandlerCollection $eventHandlers */
$eventHandlers = Projectionist::allEventHandlers();
return $eventHandlers->asyncEventHandlers()->count() > 0;
}
```
However, as it is getting all event …
> shouldDispatchJob to only count async handlers which handle the current stored event

- README.md
Needed some documentation, but got a `This site can’t be reached` on https://docs.spatie.be.
> Repaired URLs to current documentation version.

- docs/using-aggregates/testing-aggregates.md
Add a line break so use statement and call to static method are on separate lines
> Add line break to increase readability

- database/migrations/create_stored_events_table.php.stub
Changed the `event_version` column type from int to unsigned tinyint in the `stored_events` table migration stub.
The event version shouldn't be negative, therefore, the new column type would be more semantically correct for the use-case of this feature
> Change event_version column type from int to unsigned tinyint

- .github/workflows/run-tests.yml
- composer.json
- src/Support/CarbonNormalizer.php
- src/Support/ModelIdentifierNormalizer.php
The `league/flyststem` requirement had to be widened to include `^2.0` as well. However, I noticed that we're not using any code from that package explicitly anyway, so I removed it.
EDIT:
I accidentally based this PR on an older version of the package. I see that it's blocked by https://github.com/spatie/better-types now, as it requires `illuminate/collections:^8.58`, but I've also opened a PR to address this issue https://github.com/spatie/better-types/pull/2.
> Laravel 9.x Compatibility

- composer.json
- src/StoredEvents/Models/EloquentStoredEvent.php
- tests/Models/StoredEventTest.php
As noted in #270 and #271, there is a bug with the `EloquentStoredEvent` model that causes meta data changes to not be passed on to projectors and reactors the first time the event handled. Subsequent replays will correctly pass the meta data since the "cached" original event is re-created based on meta data in the database. This was a bug originally introduced in #158.
This PR provides a test for the expected functionality and a fix for the bug. The current approach being to check if the `meta_data` attribute is dirty and update the original event if so. While we could add a check for other attributes on the model, I don't think we gain as much value by doing so since those should basically be immutable.
**Side note:** I removed the unused Psalm script from the composer file since it …
> Resolves issue with meta data updating on original event.

- src/StoredEvents/Models/EloquentStoredEventQueryBuilder.php
- tests/Models/EloquentStoredEventQueryBuilderTest.php
This PR adds two methods `wherePropertyIs()` and `wherePropertyIsNot()` to the stored event query builder. These allow you to perform lookups against event properties and utilize the `whereJsonContains` methods. As an example, we have had to use this when querying for all events for a company.
**Example:**
```php
EloquentStoredEvent::query()
->whereEvent(CompanyOptedOutOfEmails::class)
->wherePropertyIs('companyId', 'ABC-123-XYZ')
->get();
```
> Adds query helpers for event properties

- src/StoredEvents/Models/EloquentStoredEventQueryBuilder.php
- tests/Models/EloquentStoredEventQueryBuilderTest.php
It is a common practice, particularly when using event queries, to retrieve the last event from the database. This pull request adds the helper `lastEvent` to the `EloquentStoredEventQueryBuilder` which will retrieve the last recorded event. For added developer experience, it accepts specific event classes for parameters and passes these to the `whereEvent` method.
> Adds last event helper

- config/event-sourcing.php
URL pointed to v5. This PR fixes it to v7
> Fix URL to documentation about caching

- docs/advanced-usage/replaying-events.md
This simply fixes a typo. The `createdAt()` method on `ShouldBeStored` is actually `camel case` and not `snake case` like the column name.
> Docs: createdAt() method is camel case

- database/migrations/create_snapshots_table.php.stub
- database/migrations/create_stored_events_table.php.stub
- tests/TestCase.php
Since minimum Laravel is v9, we can enforce to use closure migration
> Update migration file to closure

- src/AggregateRoots/FakeAggregateRoot.php
- tests/FakeAggregateRootTest.php
Hi there! I'm in the process of upgrading an application that ran on v4 this package. The test suite depends quite heavily on `FakeAggregateRoot` to assert that events get recorded or not.
Jumping major versions from v5 to v6 broke a bunch of these tests, and I suspect it happened when [v6.0.1](https://github.com/spatie/laravel-event-sourcing/releases/tag/6.0.1) no longer persisted the aggregate root in `FakeAggregateRoot::given()`.
Inadvertently, a side-effect of persisting was also removed: the recorded events on the AggregateRoot would be cleared. That effectively excluded given events from assertions about recorded events. This was compensated for in `FakeAggregateRoot::getRecordedEventsWithoutUuid()`, but not in other methods that accessed recorded events on the aggregate root.
This …
> Do not assert events given to FakeAggregateRoot as recorded

- src/Projections/Projection.php
[According to phpDocumentor docs](https://docs.phpdoc.org/3.0/guide/references/phpdoc/tags/method.html) correct placement of return type is before method name, like in C. Checked in PhpStorm - it didn't worked with trailing return type.
Also, both `EloquentStoredEventQueryBuilder` and `EloquentStoredEvent` have correct return type placement in their magic method declarations.
> Fix method annotations in Projection class

- src/AggregateRoots/AggregateRoot.php
In a project I'm working on we've added `Illuminate\Support\Traits\Tappable` to our `AggregateRoot`. However, since upgrading to v7, the `Handlers` utility finds `tap` as an acceptable method for applying events.
The type of the `$callable` parameter of `tap` is resolved as `mixed` as it is only typed with an annotation.
In this case this is unexpected behaviour as a `StoredEvent` is never callable. This PR adds an exclusion of `tap` to the resolving of handlers for commands and events.
> Exclude `tap` from possible handlers

- docs/using-reactors/creating-and-configuring-reactors.md
The method stated in the docs for getting the aggregate uuid inside a reactor is not up to date with the latest changes. In fact, adding a second parameter to the reactor will cause it to not fire at all.
> Update Reactor docs on how to get the aggregate uuid

- docs/advanced-usage/replaying-events.md
- src/Console/ReplayCommand.php
- src/Projectionist.php
- tests/Console/ReplayCommandTest.php
This MR adds an `--aggregate-uuid=` option to the `event-sourcing:replay` command. When used, the replay command will only replay events for that specific aggregate root uuid.
For context, we use this in order to speed up the replaying process, by running multiple jobs in parallel, each job replaying one specific aggregate uuid.
> Update event-sourcing:replay command to work with just one aggregate uuid

- docs/using-projectors/making-sure-events-get-handled-in-the-right-order.md
- docs/using-reactors/creating-and-configuring-reactors.md
- src/EventHandlers/EventHandlerCollection.php
- tests/EventSerializers/EventSerializerTest.php
- tests/ProjectionistTest.php
- tests/TestClasses/ProjectorWithWeightTestHelper.php
- tests/TestClasses/Projectors/ProjectorWithHighWeight.php
- tests/TestClasses/Projectors/ProjectorWithLowWeight.php
- tests/TestClasses/Projectors/ProjectorWithNegativeWeight.php
- tests/TestClasses/Projectors/ProjectorWithoutWeight.php
This is a lightweight (🥁) solution to allow package users to tweak the order projectors and reactors will run.
> Support weight property to event handlers

- src/Snapshots/EloquentSnapshotRepository.php
- tests/AggregateRootTest.php
If two snapshots are created within the same second, the retrieval method will fetch the first one, not the last one.
Any remaining events are still applied afterwards so the aggregate is consistent, but it means the snapshot effect didn't completely encapsulate the state at the time as expected.
The test confirms that no events needed to be applied after the snapshot is retrieved.
> Use the snapshot with the highest ID

- src/StoredEvents/Models/EloquentStoredEventQueryBuilder.php
- tests/Models/EloquentStoredEventQueryBuilderTest.php
This pull request fixes a bug with retrieving the last event when two events exist with the same timestamp. We ran into this issue when two events occurred at the exact same time and the event query failed to pull the proper information in.
> Fixes bug with retrieving last event

- docs/advanced-usage/discovering-projectors-and-reactors.md
- docs/advanced-usage/replaying-events.md
- docs/advanced-usage/storing-metadata.md
- docs/getting-familiar-with-event-sourcing/introduction.md
- docs/getting-familiar-with-event-sourcing/the-traditional-application.md
- docs/getting-familiar-with-event-sourcing/using-aggregates-to-make-decisions-based-on-the-past.md
- docs/getting-familiar-with-event-sourcing/using-projectors-to-transform-events.md
- docs/installation-setup.md
- docs/using-aggregates/writing-your-first-aggregate.md
- docs/using-projectors/creating-and-configuring-projectors.md
- docs/using-projectors/thinking-in-events.md
- docs/using-reactors/writing-your-first-reactor.md
Fix documentation version cross-linking to other versions for v7. #396
All of the updated links/files seem to exist in the current branch too so no edits needed.
If we're happy with this one, I can pick up tidying up the older version branches too.
> Fix documentation version cross-linking to other versions for v7. #396

- README.md
For #396 I missed the outdated links in the README.md as I had constrained my search to the docs folder.
See: https://github.com/spatie/laravel-event-sourcing/pull/402
> Fix README.md version cross-linking to other versions for v7. #396

- src/StoredEvents/StoredEvent.php
- tests/AggregateRootTest.php
- tests/TestClasses/AggregateRoots/Reactors/DoubleBalanceReactor.php
When firing event from reactor, dispatched event should go after event that triggered the reactor. Example:
`MoneyAdded -> DoubleBalanceReactor -> MoneyMultiplied`
currently dispatches events to the bus `MoneyMultiplied` first. This PR fixes that behaviour.
> Fix preserving event order when dispatched from aggregate root via event handler

- src/Support/CarbonNormalizer.php
- src/Support/ModelIdentifierNormalizer.php
- src/Support/ObjectNormalizer.php
Symfony serializer 6.3 triggers a deprecation error when a normalizer does not define a `getSupportedTypes` method or when a call is made to `hasCacheableSupportsMethod` on a Symfony provided normalizer.
https://github.com/symfony/serializer/compare/6.2...v6.3.0#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR13
https://github.com/symfony/serializer/compare/6.2...v6.3.0#diff-51c0e7020499be2a667ccb570a642fca293da2451cca31cec2ecc467ecf58b51R37
https://github.com/symfony/serializer/compare/6.2...v6.3.0#diff-05d8706b90462cdef57865a942e5a6a6bbb87924ee9830fb94555a6022607d73R63
Examples:
```
ErrorException: Since symfony/serializer 6.3: "Spatie\EventSourcing\Support\CarbonNormalizer" should implement "NormalizerInterface::getSupportedTypes(?string $format): array". in …
```
> Fix Symfony Serializer Deprecation Warnings

- docs/advanced-usage/commands.md
Updated to show that commands not longer implement `Spatie\Shop\Support\EventSourcing\Commands\Command` interface
> Correcting Commands Documentation

- src/Projectionist.php
- tests/ProjectionistTest.php
Currently, it is possible to add weights to projectors. This is also documented in: https://spatie.be/docs/laravel-event-sourcing/v7/using-projectors/making-sure-events-get-handled-in-the-right-order#content-tweaking-projector-order
However, the documentation does not mention that weights do not work when replaying events. Yet it can be assumed by default.
This sorting is useful when certain projections depend on others. **For illustration purposes**, here is a simple example:
1. Imagine there are two events `UserCreated` and `UserEmailUpdated`. They are projected with a `UserProjector`.
On every event, the projector class either saves a new user projection or updates the current entry.
Our `users` table, could look something like this:
```
| id  | uuid | email             | …
```
> Sort projectors by weight when replaying

- src/Console/ReplayCommand.php
- tests/Console/ReplayCommandTest.php
ReplayCommand `--stored-event-model` option is not implemented even though it's [documented](https://spatie.be/docs/laravel-event-sourcing/v7/advanced-usage/replaying-events).
> If you are [using your own event storage model](https://spatie.be/docs/laravel-event-sourcing/v7/advanced-usage/using-your-own-event-storage-model/) then you will need to use the --stored-event-model option when executing event-sourcing:replay to specify the model storing the events you want to replay.
This option would be especially useful when the application stores events in different tables depending on the domain. In this scenario, specifying the custom model in the config doesn't work since the custom model will be dynamically determined based on the domain.
Related discussion: …
> Replay events with custom stored event model

- src/AggregateRoots/AggregatePartial.php
Just like the `recordThat` on the `aggregateRoot` abstract class.
> Make the aggregatePartial recordThat method fluent

- src/AggregateRoots/AggregateRoot.php
There's a subtle difference between how aggregate roots discover handler methods versus how interfaces & projectors do. Because of this, type hinting an interface implemented on an event works in projectors & reactors, but not aggregate roots.
This PR changes `AggregateRoot::apply` to be consistent with `HandlesEvents::handle`.
> Support interfaces in aggregate root apply methods

- src/AggregateRoots/AggregateRoot.php
- src/EventHandlers/AppliesEvents.php
- src/EventHandlers/HandlesEvents.php
- tests/AggregateRootTest.php
- tests/AggregateRoots/CommandHandlerTest.php
- tests/Commands/CommandBusTest.php
- tests/TestClasses/AggregateRoots/AccountAggregateRoot.php
- tests/TestClasses/AggregateRoots/StorableEvents/MoneyAddedInterface.php
- tests/TestClasses/AggregateRoots/StorableEvents/MoneyIncremented.php
Fixes #437. Essentially if you'll accept null you're too accepting (un-typed params, variadics etc.) I also added a test to check handling interfaces still works.
> Added an extra rejection to prevent events being passed to invalid handlers

- config/event-sourcing.php
- src/AggregateRoots/AggregatePartial.php
- src/AggregateRoots/AggregateRoot.php
- tests/AggregateRootTest.php
- tests/TestClasses/AggregateRoots/AccountAggregateRootWithPartial.php
- tests/TestClasses/AggregateRoots/Partials/MoneyPartial.php
This pull request is an attempted, updated fix for issue #307 where the states of partials are not restored when a snapshot is retrieved.
This update works by defining a single key (default `__esPartials`) in the event sourcing config file that is used as a key in the state of a snapshot. Each partial is then reflected for public properties, and a key that is the classname of the partial is added to the `__esPartials` in the generated. The value of that key is the state of the partial.
This will generate a snapshot state of:
```php
$state = [
'foo' => 'bar',
'__esPartials' => [
'App/Partials/FooPartial' => [
'fooProperty1' => 1,
'fooProperty2' => true
],
];
````
Reconstitution of the snapshot goes through each key of __esPartials and matches to a resolved Partial Class, and sets the state …
> Fix snapshots in aggregate partials

- src/Support/DiscoverEventHandlers.php
- tests/TestClasses/AutoDiscoverEventHandlers/AbstractProjector.php
- tests/TestClasses/AutoDiscoverEventHandlers/AbstractReactor.php
This PR filters out abstract projectors and reactors, so that application code can use abstract subclasses.
> Ignore abstract event handlers

- docs/introduction.md
- docs/using-aggregates/creating-and-configuring-aggregates.md
- docs/using-projectors/making-sure-events-get-handled-in-the-right-order.md
- docs/using-projectors/writing-your-first-projector.md
- docs/using-reactors/creating-and-configuring-reactors.md
Address various typos and make grammatical improvements in the documentation to enhance its accuracy.
> Address Typos and Make Grammatical Improvements in Documentation

- .github/workflows/php-cs-fixer.yml
- .github/workflows/run-tests.yml
- .github/workflows/update-changelog.yml
Update actions/checkout to v4
[actions/checkout/releases/v4.0.0](https://github.com/actions/checkout/releases/tag/v4.0.0)
> Update actions/checkout to v4

- docs/advanced-usage/preparing-events.md
Currently the documentation tells you to implement an non-exsting interface. This change updates the documentation according to the code.
> Document prepare events using abstract class instead of interface

- database/migrations/create_snapshots_table.php.stub
Just started using this package for the first time for a new project. 
Noticed the two migrations that are included have a different column type for what appears to be the same data. (As the snapshot's aggregate_version always seems to match the corresponding event's aggregate_version).
I decided to use the bigger data type of the two as this seemed like the safer option.
> Change the column type of snapshots.aggregate_version

- .github/workflows/run-tests.yml
- .gitignore
- composer.json
- phpunit.xml.dist
- src/Support/CarbonNormalizer.php
- src/Support/ModelIdentifierNormalizer.php
- src/Support/ObjectNormalizer.php
[symfony/serializer](https://github.com/symfony/serializer) made the `Symfony\Component\Serializer\Normalizer\ObjectNormalizer` class final and now requires to implement some of the core methods. 
We still only needed to change `getSupportedTypes()` so rather than copy in whole function bodies I just grabbed an instance of their `ObjectNormalizer` and used it for the rest.
> L11 compatibility

- composer.json
- src/StoredEvents/StoredEvent.php
> AllowDynamicProperties to suppress PHP warnings on 8.2

- config/event-sourcing.php
- docs/advanced-usage/using-aliases-for-stored-event-classes.md
- docs/installation-setup.md
- src/StoredEvents/Exceptions/EventClassMapMissing.php
- src/StoredEvents/Repositories/EloquentStoredEventRepository.php
- tests/Models/StoredEventTest.php
Like with `Relation::enforceMorphMap` i added a config option to always throw an exception if an event without alias is persisted. 
Thank you for the great package if you have questions or change requests I am happy to update the PR.
> Add config to enforce every event has an alias.

- src/StoredEvents/Repositories/EloquentStoredEventRepository.php
- tests/EloquentStoredEventRepositoryTest.php
- tests/TestClasses/EventSerializer/DummySerializer.php
- tests/TestClasses/Events/EventWithCustomSerializer.php
I stumbled upon issue #414 while setting up custom event serializers.
This PR fixes this issue by also using the custom event serializer while persisting events.
If you have any questions, please reach out to me!
I don't know if the previous behavior was a bug or intentional, but "fixing" it changes how events are serialized into the database. Therefore, it probably makes sense to release this in a major version update.
> Use custom serializer while persisting events

- docs/advanced-usage/replaying-events.md
- docs/advanced-usage/storing-metadata.md
- docs/getting-familiar-with-event-sourcing/introduction.md
- docs/getting-familiar-with-event-sourcing/using-aggregates-to-make-decisions-based-on-the-past.md
- docs/getting-familiar-with-event-sourcing/using-projectors-to-transform-events.md
- docs/installation-setup.md
- docs/introduction.md
- docs/using-aggregates/writing-your-first-aggregate.md
- docs/using-projectors/creating-and-configuring-projectors.md
- docs/using-projectors/thinking-in-events.md
- docs/using-reactors/writing-your-first-reactor.md
Internal links in hosted documentation link to 404 as `/docs` prefix is missing in linked url. This change adds the `/docs` prefix to all internal links.
> fix: internal links use /docs prefix

- src/StoredEvents/StoredEvent.php
Adding this message makes debugging easier during event replay.
-- 
Before
```
Replaying 44037 events...
37995/44037 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░]  86%
Spatie\EventSourcing\StoredEvents\Exceptions\InvalidStoredEvent 
at vendor/spatie/laravel-event-sourcing/src/StoredEvents/StoredEvent.php:121
117▕ 
118▕         try {
119▕             $reflectionClass = new ReflectionClass($this->event_class);
120▕         } catch (ReflectionException $exception) {
➜ 121▕             throw new InvalidStoredEvent();
122▕         }
123▕ 
124▕         if ($serializerAttribute = $reflectionClass->getAttributes(EventSerializerAttribute::class)[0] ?? null) {
125▕             $serializerClass = ($serializerAttribute->newInstance())->serializerClass;
+20 vendor frames 
21  artisan:35 …
```
> Add reflection exception error message to InvalidStoredEvent exception

- docs/installation-setup.md
I just copied from the published config. The one at https://spatie.be was showing `use` statements at the top of the file and they were all formatted into a single line without breaks.
The actual config just uses fully qualified class names.
> Update installation-setup.md to match actual contents of config/event-sourcing.php

- docs/using-reactors/creating-and-configuring-reactors.md
Seems like the creating-and-configuring-reactors,md file was created by copying the same file from the using-projectors directory, and some instances of "projector" were left in tact without being replaced by "reactor".
This PR fixes that documentation issue.
> Replace 'projector' with 'reactor' where necessary.

- src/StoredEvents/StoredEvent.php
- tests/EventSubscriberTest.php
- tests/TestClasses/Projectors/QueuedProjector.php
This PR modifies the condition under which the handle stored event job is dispatched to the queue. 
With the pre-existing behavior, a job is dispatched each time an event persists if the projectionist has any async handlers registered, even if the specific event is irrelevant to all async handlers.
My application has certain events that contain a lot of data. These events do not have async handlers. Serializing these events to the queue (for what is ultimately a noop job) has resulted in errors due to SQS payload limits.
I also have some high-volume events that do not have async handlers, leading to unnecessary excessive queue throughput.
This change ensures a job is only dispatched if the fired event has async handlers.
> Only Dispatch If Event Has Async Handler

- src/StoredEvents/Models/EloquentStoredEventQueryBuilder.php
- src/StoredEvents/StoredEvent.php
When using an `event_class_map` and querying `->whereEvent(...)`, all given events should be mapped to their corresponding value before querying the database.
> Use class map name when querying event class

- src/EventSourcingServiceProvider.php
[Newly introduced in Laravel 11.27](https://github.com/laravel/framework/pull/52928), packages can now register the commands that should run during the `optimize` phase of deployment.
This PR adds the recommended steps for optimizing whenever it's available.
> Register optimize commands

- src/EventSourcingServiceProvider.php
This PR aims to fix a problem in the `EventSourcingServiceProvider:54`, where the clear command is typed differently from the command signature.
> update command name to match class name

- docs/advanced-usage/using-your-own-event-serializer.md
- src/EventSerializers/EventSerializer.php
- src/EventSerializers/JsonEventSerializer.php
Fixed the remaining missing ?string definitions for the metadata parameter in EventSerializer, JsonEventSerializer, and the documentation example for consistency.
> Fix Remaining Nullable Parameter Definitions

- src/StoredEvents/Models/EloquentStoredEvent.php
- src/StoredEvents/Models/EloquentStoredEventCollection.php
- src/StoredEvents/Models/EloquentStoredEventQueryBuilder.php
This is useful when using PHPStan in your project in combination with the `EventQuery` classes.
> feat: add eloquent stored event generic types for collection and query builder

- docs/using-projectors/writing-your-first-projector.md
Hi there,  
While reading the documentation on event sourcing, I noticed some mistakes and wanted to contribute by fixing them😊
> docs: fix method name inconsistencies and usage corrections

- src/AggregateRoots/AggregateRoot.php
With Postgres, the error message thrown for a unique constraint violation doesn't have a capital D
```
SQLSTATE[  23505]: Unique violation:   7 ERROR:  duplicate key value violates unique constraint 
```
> Case insensitive CouldNotPersistAggregate::invalidVersion detection

- docs/advanced-usage/using-your-own-event-serializer.md
**Context:**  
The documentation for using a custom event serializer was outdated and inconsistent with the updated `EventSerializer` interface.
**Changes Introduced:**  
- Added PHP syntax highlighting to code blocks for better readability.
- Updated the `EventSerializer` interface method signature:
- `deserialize` now accepts an additional `int $version` parameter.
- Made `$metadata` optional and nullable.
- Adjusted the example `UpgradeSerializer` class:
- Updated its `deserialize` method signature to match the new interface.
- Added a conditional check to apply currency defaulting logic only for the `MoneyAdded` event class.
**Impact:**  
This update ensures developers extending or overriding the event serializer have accurate references, No breaking changes to codebase functionality.
> [Docs] Add Missing Version Property in Event Serializers

- src/EventSourcingServiceProvider.php
- tests/DiscoversEventHandlersTest.php
@freekmurze 
1. When deployed to production, the file will execute `php artisan optimize` to generate the `event-handlers.php` file.
2. Due to requirement changes, I deleted the `App\\Bookings\\Projector\\BookingsProjector` class, but the event-handlers.php file is not being updated.
3. During redeployment, an exception was triggered because `App\Bookings\Projector\BookingsProjector` is still registered in the `event-handlers.php` file, causing the `php artisan` command to fail and resulting in deployment failure.
> Filter out non-existent classes from cached event handlers

- src/Projectionist.php
According to the documentation in `config/event-sourcing.php:43-47`:
```
/*
* When a Projector or Reactor throws an exception the event Projectionist can catch it
* so all other projectors and reactors can still do their work. The exception will
* be passed to the `handleException` method on that Projector or Reactor.
*/
```
But if the feature is activated, the current implementation catches the exception _and_ aborts further event handling. This happens because the method returns false, and in this case the Laravel Collection stops the loop (see here 
[/Illuminate/Collections/Traits/EnumeratesValues.php#L268](https://github.com/laravel/framework/blob/920724c150c8d63fa5a96a5e3f0afe10f4e111bd/src/Illuminate/Collections/Traits/EnumeratesValues.php#L268)).
This creates a situation where the …
> Projectionist: Don't stop handling events when catching exceptions
