- docs/installation-setup.md
> Changed laravel-event-sourcing version

- config/event-sourcing.php
Fixes the documentation on Advanced Usage link
> Fixes documentation link

- docs/installation-setup.md
> Update docs with horizon example

- docs/getting-familiar-with-event-sourcing/using-projectors-to-transform-events.md
I believe this corrects what the paragraph was trying to say.
> Slightly confusing paragraph

- docs/using-reactors/creating-and-configuring-reactors.md
It was displaying ok on Github but not on the documentation site.
> Add closing code block syntax

- README.md
Thank you for your awesome packages.
> Fix broken link to UPGRADING.md file

- docs/using-aggregates/creating-snapshots.md
- docs/using-aggregates/snapshots.md
> Add docs for snapshotting

- docs/using-aggregates/testing-aggregates.md
Thanks for the great packages, fixed a few minor issues I ran into when going through the testing docs. Hopefully makes them a little better.
> Fix testing aggregates docs

- config/event-sourcing.php
- src/DiscoverEventHandlers.php
- src/EventSourcingServiceProvider.php
Refactor incompatible methods for lumen support
> Refactor incompatible methods for lumen support

- src/FakeAggregateRoot.php
added a getter method to FakeAggregateRoot
> expose AggregateRoot for testing state

- .github/workflows/run-tests.yml
Signed-off-by: Sohaib LAFIFI <sohaib.lafifi@univ-artois.fr>
> start Mysql service before creating db for github action

- docs/installation-setup.md
Came across this while installing the package. Thank you for everything you do :heart:
> Fix missing word in installation setup docs

- config/event-sourcing.php
> Fix typo in config/event-sourcing.php

- docs/advanced-usage/allowing-concurrent-persists.md
A PR seems to be sort of an overkill for a tiny duplication, but as I just stumbled over it.
> fixed typo

- src/AggregateRoot.php
This allows better static analysis.
> Add static return type for AggregateRoot::retrieve

- docs/advanced-usage/adding-and-removing-projectors-and-reactors.md
- docs/advanced-usage/discovering-projectors-and-reactors.md
- docs/advanced-usage/handling-exceptions.md
- docs/advanced-usage/storing-metadata.md
- docs/advanced-usage/using-aliases-for-stored-event-classes.md
- docs/using-aggregates/writing-your-first-aggregate.md
- docs/using-projectors/writing-your-first-projector.md
- docs/using-reactors/creating-and-configuring-reactors.md
- src/AggregateRoot.php
> Typo’s, spelling corrections, indent fixes and such

- src/StoredEvent.php
> Relax property type of meta_data

- docs/using-aggregates/snapshots.md
The rejection clause was included in the source code, but not in the documentation.
> Added rejection clause to getState for snapshots

- src/AggregateRoot.php
- tests/AggregateRootTest.php
- tests/TestClasses/AggregateRoots/AccountAggregateRoot.php
By resolving the class from Laravel's IoC.
> Allow aggregate roots to have dependencies in constructor

- src/AggregateRoot.php
'resolve()' helper does not exist in Lumen.
> lumen support

- docs/installation-setup.md
- docs/questions-issues.md
Documentation corrections
1. Example config changes - base model name, EventSerializer Interface name in the comment
2. Package name in Questions and Issues
> Documentation corrections

- CHANGELOG.md
- docs/using-aggregates/testing-aggregates.md
- src/AggregateRoots/FakeAggregateRoot.php
- tests/FakeAggregateRootTest.php
> Support closures in assert recorded

- docs/using-projectors/writing-your-first-projector.md
> Clarify parameter name on type hint

- src/Projectionist.php
Add type hint to add certainty on call-site.
> Add type hint for add projector method

- docs/introduction.md
> Update the docs to mention the launched course

- docs/using-projectors/writing-your-first-projector.md
The value should be decremented on the `MoneySubtracted` event.
> [Docs] Fix wrong operator for onMoneySubtracted

- docs/using-projectors/writing-your-first-projector.md
... and thus count should go up
> Typo fix in documentation - subtracting is also a transaction

- docs/requirements.md
In your most recent commit for the composer.json, you mentioned you removed laravel 8 compatibility
> Updated the requirement to Laravel 9

- config/event-sourcing.php
This PR make cache_path of this package same as laravel cache path
> Update cache_path in config

- docs/using-projectors/creating-and-configuring-projectors.md
Following the docs as they are currently causes your projector to not run. Took me a while to figure out this was the reason so felt the docs need to be updated.
> Update Projector docs to reflect changes to getting the aggregate uuid

- docs/using-projectors/making-sure-events-get-handled-in-the-right-order.md
- docs/using-reactors/creating-and-configuring-reactors.md
- src/EventHandlers/EventHandlerCollection.php
- tests/ProjectionistTest.php
- tests/TestClasses/ProjectorWithWeightTestHelper.php
- tests/TestClasses/Projectors/ProjectorWithHighWeight.php
- tests/TestClasses/Projectors/ProjectorWithLowWeight.php
- tests/TestClasses/Projectors/ProjectorWithNegativeWeight.php
- tests/TestClasses/Projectors/ProjectorWithoutWeight.php
> Support weight property to event handlers

- docs/using-projectors/thinking-in-events.md
- docs/using-projectors/writing-your-first-projector.md
Discovered this helpful class in the Event Sourcing in Laravel book which isn't documented in the `docs`, so I have added it here.
> Document the use of the Projection class

- docs/using-projectors/writing-your-first-projector.md
As per https://github.com/spatie/laravel-event-sourcing/pull/369#issuecomment-1541848380
> Expand documentation for projection factories

- docs/using-projectors/creating-and-configuring-projectors.md
- docs/using-reactors/creating-and-configuring-reactors.md
This PR corrects typos in docs
> Corrects typos in docs

- src/Projectionist.php
I forgot one in my previous [PR](https://github.com/spatie/laravel-event-sourcing/pull/493)
> Explicitly mark variable nullable
